#include <stdio.h> 
#include <stdlib.h>

#include <SDL.h>

#include "keypress.h"
#include "struct.h" 


struct field map[15][15] = {
	{{FIELD_WATER},{FIELD_WATER2},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2},{FIELD_GRASS},{FIELD_GRASS2},{FIELD_GRASS2},{FIELD_GRASS3},{FIELD_MOUNTAIN3},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2}},
	{{FIELD_WATER},{FIELD_WATER2},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2},{FIELD_GRASS},{FIELD_GRASS2},{FIELD_GRASS2},{FIELD_GRASS3},{FIELD_MOUNTAIN3},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2}},
	{{FIELD_WATER},{FIELD_WATER2},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2},{FIELD_GRASS},{FIELD_GRASS2},{FIELD_GRASS2},{FIELD_GRASS3},{FIELD_MOUNTAIN3},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2}},
	{{FIELD_WATER},{FIELD_WATER2},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2},{FIELD_GRASS},{FIELD_GRASS2},{FIELD_GRASS2},{FIELD_GRASS3},{FIELD_MOUNTAIN3},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2}},
	{{FIELD_WATER},{FIELD_WATER2},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2},{FIELD_GRASS},{FIELD_GRASS2},{FIELD_GRASS2},{FIELD_GRASS3},{FIELD_MOUNTAIN3},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2}},
	{{FIELD_WATER},{FIELD_WATER2},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2},{FIELD_GRASS},{FIELD_GRASS2},{FIELD_GRASS2},{FIELD_GRASS3},{FIELD_MOUNTAIN3},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2}},
	{{FIELD_WATER},{FIELD_WATER2},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2},{FIELD_GRASS},{FIELD_GRASS2},{FIELD_GRASS2},{FIELD_GRASS3},{FIELD_MOUNTAIN3},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2}},
	{{FIELD_WATER},{FIELD_WATER2},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2},{FIELD_GRASS},{FIELD_GRASS2},{FIELD_GRASS2},{FIELD_GRASS3},{FIELD_MOUNTAIN3},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2}},
	{{FIELD_WATER},{FIELD_WATER2},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2},{FIELD_GRASS},{FIELD_GRASS2},{FIELD_GRASS2},{FIELD_GRASS3},{FIELD_MOUNTAIN3},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2}},
	{{FIELD_WATER},{FIELD_WATER2},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2},{FIELD_GRASS},{FIELD_GRASS2},{FIELD_GRASS2},{FIELD_GRASS3},{FIELD_MOUNTAIN3},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2}},
	{{FIELD_WATER},{FIELD_WATER2},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2},{FIELD_GRASS},{FIELD_GRASS2},{FIELD_GRASS2},{FIELD_GRASS3},{FIELD_MOUNTAIN3},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2}},
	{{FIELD_WATER},{FIELD_WATER2},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2},{FIELD_GRASS},{FIELD_GRASS2},{FIELD_GRASS2},{FIELD_GRASS3},{FIELD_MOUNTAIN3},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2}},
	{{FIELD_WATER},{FIELD_WATER2},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2},{FIELD_GRASS},{FIELD_GRASS2},{FIELD_GRASS2},{FIELD_GRASS3},{FIELD_MOUNTAIN3},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2}},
	{{FIELD_WATER},{FIELD_WATER2},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2},{FIELD_GRASS},{FIELD_GRASS2},{FIELD_GRASS2},{FIELD_GRASS3},{FIELD_MOUNTAIN3},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2}},
	{{FIELD_WATER},{FIELD_WATER2},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2},{FIELD_GRASS},{FIELD_GRASS2},{FIELD_GRASS2},{FIELD_GRASS3},{FIELD_MOUNTAIN3},{FIELD_GRASS},{FIELD_GRASS},{FIELD_MOUNTAIN3},{FIELD_MOUNTAIN2}},
};

void drawmap(SDL_Surface *mapsur,SDL_Surface *fieldsur)
{
	for(int x=0;x<15;x++)
	{
		for(int y=0;y<15;y++)
		{
			enum FieldType type=map[y][x].type;
			SDL_Rect srcrect={type*30,0,30,30};
			SDL_Rect dstrect={x*30,y*30,30,30};
			SDL_BlitSurface(fieldsur,&srcrect,mapsur,&dstrect);
		}
	}
}

int main(int argc, char **argv)
{
	SDL_Window *screen;
	SDL_Surface *fieldsur;
	SDL_Surface *scresur;

	//Initalize Screen
	SDL_Init(SDL_INIT_EVERYTHING);
	screen = SDL_CreateWindow("G@ME", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED,
	                          640, 480, SDL_WINDOW_SHOWN);
	if(!screen)
	{
		SDL_GetError();
	}
	else
	{
		scresur = SDL_GetWindowSurface(screen);
	}
	
	//Loading map tiles on fieldsur
	fieldsur=SDL_LoadBMP("field.bmp");
	if(!fieldsur)
	{
		SDL_ShowSimpleMessageBox(0,"Error",SDL_GetError(),screen);
		return 1;
	}
	//using drawmap on scresur with the maptiles from fieldsur
	drawmap(scresur,fieldsur);

	SDL_UpdateWindowSurface(screen);
	SDL_Delay(5000);
		
    	SDL_FreeSurface(fieldsur);    
    	SDL_DestroyWindow(screen);

	SDL_Quit();

	return 0;
}
