#ifndef __GME_STRUCT_H
#define __GME_STRUCT_H

struct field {
	enum FieldType {
		FIELD_WATER = 0,
		FIELD_WATER2,
		FIELD_WATER3,
		FIELD_WATER4,
		FIELD_WATER5,
		FIELD_GRASS,
		FIELD_GRASS2,
		FIELD_GRASS3,
		FIELD_GRASS4,
		FIELD_MOUNTAIN,
		FIELD_MOUNTAIN2,
		FIELD_MOUNTAIN3,
		FIELD_MOUNTAIN4,
		FIELD_MOUNTAIN5
	} type;
};

#endif
